
import type { Expert } from '@/types';
import { Brain, Bot, Eye, MessageCircle, Shield, Layers, Sparkles, Users, TrendingUp, Repeat, UserCog, Briefcase, Scale, Landmark, Lightbulb, BarChart3, PencilLine, Cpu, SearchCode, Microscope, UsersRound, Network, Speech, Sigma, Globe, Palette, Link2, Lock, Code, Aperture, GitBranch, Server, Cloud, Database, Keyboard, Monitor, BookOpen, FileText, DollarSign, Zap, Building, University, Filter, Megaphone, ShieldCheck, Target, Anchor, Group, Shuffle, Info, AlertTriangle, Drama, Library, FlaskConical, LifeBuoy } from 'lucide-react';

export const expertiseIcons: { [key: string]: React.ElementType } = {
  'Machine Learning': Brain,
  'Robotics': Bot,
  'Computer Vision': Eye,
  'Natural Language Processing': MessageCircle,
  'AI Ethics': Shield,
  'Deep Learning': Layers,
  'AGI Research': Sparkles,
  'Reinforcement Learning': Repeat,
  'AI Strategy': UserCog, // Changed from Users to UserCog for more specific meaning
  'AI Investment': TrendingUp,
  'Default': Lightbulb, // Changed from Sparkles to Lightbulb for a more generic default
  'Neural Networks': Network, // Changed from Layers
  'AI Governance': Scale, // Changed from Shield
  'Large Language Models': FileText, // Changed from MessageCircle
  'Computational Linguistics': MessageCircle,
  'Image Recognition': Aperture, // Changed from Eye
  'Cognitive Architectures': Brain,
  'Human-Robot Interaction': UsersRound, // Changed from Bot
  'Mechatronics': Cpu, // Changed from Bot
  'Venture Capital': DollarSign, // Changed from TrendingUp
  'AI Startups': Building, // Changed from Users
  'AI Safety': ShieldCheck, // Changed from Shield
  'AI Policy': Landmark, // Changed from Shield
  'Transformers': Shuffle, // Changed from Layers
  'Statistics': BarChart3, // Changed from Brain
  'AI Education': BookOpen, // Changed from Users
  'Neuroscience': Brain,
  'Generative AI': Palette, // Changed from Sparkles
  'Applied AI': Zap, // Changed from Sparkles
  'Dialogue Systems': Speech, // Changed from MessageCircle
  'AI Platforms': Server, // Changed from Layers
  'Speech Recognition': Speech,
  'Interpretability': SearchCode, // Changed from Eye
  'Causal Inference': Link2, // Changed from Brain
  'GPU Technology': Cpu, // Changed from Layers
  'Democratizing AI': Globe, // Changed from Users
  'Algorithmic Bias': Filter, // Changed from Shield
  'Existential Risk': AlertTriangle, // Changed from Shield
  'Responsible AI': ShieldCheck, // Changed from Shield
  'AI Theory': Sigma, // Changed from Brain
  'Search Algorithms': SearchCode, // Changed from Layers
  'Behavior-based AI': Bot,
  'Embodied AI': Bot,
  'Self-Driving Cars': Bot, // Consider a Car icon if available
  'Probabilistic Models': BarChart3, // Changed from Brain
  'Computational Biology': Microscope, // Changed from Brain
  'AI Leadership': Users,
  'Technology Entrepreneurship': Lightbulb, // Changed from Users
  'Software Engineering': Code, // Changed from Layers
  'Generative Models': Palette, // Changed from Sparkles
  'Large-Scale Systems': Server, // Changed from Layers
  'Machine Learning Infrastructure': Database, // Changed from Layers
  'Continual Learning': Repeat,
  'AI for Science': FlaskConical, // Changed from Sparkles
  'Bayesian Methods': Sigma, // Changed from Brain
  'Human-AI Collaboration': UsersRound, // Changed from Users
  'Decision Theory': Brain,
  'Scalable AI': Cloud, // Changed from Layers
  'Optimization': Target, // Changed from Brain
  'Sequence Modeling': PencilLine, // Changed from Layers
  'AI Entrepreneurship': Lightbulb, // Changed from Users
  'Search Technology': SearchCode, // Changed from Layers
  'European AI': Globe, // Changed from Users
  'Social Technology': Users,
  'CRM Technology': Keyboard, // Changed from Layers, consider a more specific icon
  'Dynamic Control Systems': Bot,
  'AI Hardware': Cpu, // Changed from Layers
  'Fairness in AI': Scale, // Changed from Shield
  'Social Implications of AI': Group, // Changed from Shield
  'Data Studies': Database, // Changed from Brain
  'AI Impact': Zap, // Changed from Sparkles
  'Commonsense Reasoning': Brain,
  'AI Criticism': Megaphone, // Changed from MessageCircle
  'National Security': Shield,
  'AI Economics': DollarSign, // Changed from TrendingUp
  'Technology Research': Monitor, // Changed from Layers
  'Data Ethics': ShieldCheck, // Changed from Shield
  'AI for Good': LifeBuoy, // Changed from Sparkles
  'Technology Governance': Landmark, // Changed from Shield
  'International Security': Globe, // Changed from Shield
  'Rationality': Brain,
  'Philosophy of AI': Library, // Changed from Brain, consider specific philosophy icon
  'Future of AI': Sparkles,
  'Game AI': Bot, // Consider a game controller icon
  'Multi-Agent Systems': Users,
  'Efficient AI Models': Layers,
  '3D Reconstruction': Eye,
  'AI Planning': Brain,
  'Decision Making': Brain,
  'Word Embeddings': MessageCircle,
  'Explainable AI': Info, // Changed from Eye
  'Interpretable Machine Learning': Info, // Changed from Eye
  '3D Computer Vision': Eye,
  'Robot Learning': Bot,
  'Computational Photography': Aperture, // Changed from Eye
  'Graphics': Palette, // Changed from Layers
  'AI for Creativity': Palette, // Changed from Sparkles
  'Machine Translation': MessageCircle,
  'Theoretical Machine Learning': Sigma, // Changed from Brain
  'Algorithms': Code, // Changed from Layers
  'AI Security': Lock, // Changed from Shield
  'Open Source AI': GitBranch, // Changed from Users
  'Consumer AI': Users,
  'Financial AI': DollarSign, // Changed from TrendingUp
  'LSTM': PencilLine, // Changed from Layers
  'Blockchain': Link2, // Changed from Layers
  'Decentralized Systems': Network, // Changed from Layers
  'Tensor Methods': Sigma,
  'High-Performance Computing': Cpu,
  'Trustworthy AI': ShieldCheck,
  'Mobile Computing': Monitor,
  'Distributed Systems': Network,
  'Meta-Learning': Brain,
  'Kernel Methods': Sigma,
  'Knowledge Representation': FileText,
  'Facial Recognition Technology': Eye,
  'Cognitive Science': Brain,
  'Neuro-Symbolic AI': Brain,
  'Superintelligence': Sparkles,
  'Physics': Sigma, // Placeholder, consider atom or similar
  'Deep Q-Networks (DQN)': Layers,
  'Conversational AI': Speech,
  'Enterprise AI': Building,
};


export const IMPACT_AREAS_ORDERED: string[] = [
  'Pioneers & Foundational Researchers',
  'Leaders at Major AI Labs & Companies',
  'Influential Academics',
  'Key Innovators & Entrepreneurs',
  'Prominent Voices in AI Ethics & Safety',
];

export const experts: Expert[] = [
  {
    id: '1',
    name: 'Dr. Aris Thorne',
    title: 'Chief AI Ethicist, FutureForward AI',
    bio: 'Dr. Aris Thorne is a leading voice in AI ethics and responsible AI development. With over 15 years of experience, Aris focuses on creating frameworks for transparent and equitable AI systems.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Dr. Aris',
    expertise: ['AI Ethics', 'Responsible AI', 'AI Governance'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [
      { id: 'p1-1', text: 'By 2028, AI ethics boards will be mandatory for all major tech companies.', dateMade: '2023-05-10', topic: 'AI Governance' },
      { id: 'p1-2', text: 'Explainable AI (XAI) will see significant breakthroughs, making complex models more understandable.', dateMade: '2023-08-22', topic: 'Explainable AI' },
    ],
    company: 'FutureForward AI',
    linkedin: 'https://linkedin.com/in/aristhorne',
    twitter: 'https://twitter.com/aristhorne',
  },
  {
    id: '2',
    name: 'Lena Hanson',
    title: 'Lead NLP Researcher, LinguaTech',
    bio: 'Lena Hanson specializes in Natural Language Processing and computational linguistics. Her work on large language models has pushed the boundaries of machine understanding and generation.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Lena Hanson',
    expertise: ['Natural Language Processing', 'Large Language Models', 'Computational Linguistics'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [
      { id: 'p2-1', text: 'Cross-lingual understanding in LLMs will reach near human-level parity by 2027.', dateMade: '2023-01-15', topic: 'NLP' },
      { id: 'p2-2', text: 'AI-powered tools for creative writing and coding assistance will become ubiquitous in the next 3 years.', dateMade: '2023-11-02', topic: 'Generative AI' },
    ],
    company: 'LinguaTech',
    linkedin: 'https://linkedin.com/in/lenahanson',
    twitter: 'https://twitter.com/lenahanson',
  },
  {
    id: '3',
    name: 'Marcus Chen',
    title: 'Principal Investigator, Visionary Machines Lab',
    bio: 'Marcus Chen is at the forefront of Computer Vision research. His lab develops innovative algorithms for image recognition, object detection, and real-time video analysis.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Marcus Chen',
    expertise: ['Computer Vision', 'Deep Learning', 'Image Recognition'],
    impactArea: 'Influential Academics',
    predictions: [
      { id: 'p3-1', text: 'Autonomous vehicles will rely heavily on federated learning for vision systems by 2029.', dateMade: '2023-03-30', topic: 'Computer Vision' },
      { id: 'p3-2', text: 'Generative adversarial networks (GANs) for image synthesis will produce photorealistic results indistinguishable from real photos by 2026.', dateMade: '2023-09-12', topic: 'Generative AI' },
    ],
    company: 'Visionary Machines Lab',
    linkedin: 'https://linkedin.com/in/marcuschen',
    twitter: 'https://twitter.com/marcuschen',
  },
  {
    id: '4',
    name: 'Dr. Evelyn Reed',
    title: 'Director of AGI Research, Nova Dynamics',
    bio: 'Dr. Evelyn Reed leads a team dedicated to achieving Artificial General Intelligence. Her research explores novel architectures and learning paradigms for more versatile and adaptive AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Dr. Evelyn',
    expertise: ['AGI Research', 'Cognitive Architectures', 'Reinforcement Learning'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [
      { id: 'p4-1', text: 'A significant step towards AGI, demonstrating robust transfer learning across vastly different domains, will occur before 2035.', dateMade: '2022-12-01', topic: 'AGI' },
      { id: 'p4-2', text: 'Neuro-symbolic AI approaches will be critical in bridging the gap between current AI and AGI.', dateMade: '2023-07-20', topic: 'AI Architectures' },
    ],
    company: 'Nova Dynamics',
    linkedin: 'https://linkedin.com/in/evelynreed',
    twitter: 'https://twitter.com/evelynreed',
  },
  {
    id: '5',
    name: 'Kenji Tanaka',
    title: 'Robotics Innovator & CEO, Cyber шаг (Cyber Step)',
    bio: 'Kenji Tanaka is a pioneer in humanoid robotics and human-robot interaction. His company, Cyber шаг, develops advanced robotic systems for various industries, from manufacturing to healthcare.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Kenji Tanaka',
    expertise: ['Robotics', 'Human-Robot Interaction', 'Mechatronics'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [
      { id: 'p5-1', text: 'Collaborative robots (cobots) will become standard in small and medium-sized enterprises by 2030.', dateMade: '2023-02-18', topic: 'Robotics' },
      { id: 'p5-2', text: 'AI-driven robotic surgery will allow for new levels of precision and minimally invasive procedures within the next decade.', dateMade: '2023-10-05', topic: 'Healthcare AI' },
    ],
    company: 'Cyber шаг',
    linkedin: 'https://linkedin.com/in/kenjitanaka',
    twitter: 'https://twitter.com/kenjitanaka',
  },
   {
    id: '6',
    name: 'Sofia Petrova',
    title: 'AI Investment Strategist, Quantum Leap Capital',
    bio: 'Sofia Petrova identifies and invests in groundbreaking AI startups. With a keen eye for disruptive technologies, she helps shape the future of AI through strategic funding and mentorship.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Sofia Petrova',
    expertise: ['AI Investment', 'Venture Capital', 'AI Startups'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [
      { id: 'p6-1', text: 'Investment in AI for drug discovery will triple by 2027.', dateMade: '2023-06-25', topic: 'AI Investment' },
      { id: 'p6-2', text: 'Edge AI will attract significant venture capital funding as demand for on-device processing grows.', dateMade: '2023-11-15', topic: 'Edge AI' },
    ],
    company: 'Quantum Leap Capital',
    linkedin: 'https://linkedin.com/in/sofiapetrova',
    twitter: 'https://twitter.com/sofiapetrova',
  },
  {
    id: '7',
    name: 'Geoffrey Hinton',
    title: 'Pioneer in Deep Learning',
    bio: 'A "Godfather of Deep Learning," renowned for his foundational work on backpropagation, Boltzmann machines, and neural networks. Affiliated with Google and the University of Toronto.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Geoffrey Hinton',
    expertise: ['Deep Learning', 'Neural Networks', 'Machine Learning', 'Backpropagation', 'Boltzmann Machines'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'Google / University of Toronto',
  },
  {
    id: '8',
    name: 'Yann LeCun',
    title: 'Chief AI Scientist, Meta / Professor, NYU',
    bio: 'A "Godfather of Deep Learning," celebrated for inventing convolutional neural networks (CNNs), a cornerstone of modern AI. Serves as Chief AI Scientist at Meta and Professor at NYU.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Yann LeCun',
    expertise: ['Deep Learning', 'Computer Vision', 'Neural Networks', 'Convolutional Neural Networks'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'Meta / NYU',
  },
  {
    id: '9',
    name: 'Yoshua Bengio',
    title: 'Scientific Director, Mila / Professor, University of Montreal',
    bio: 'A "Godfather of Deep Learning," known for his significant contributions to deep learning, recurrent neural networks (RNNs), and attention mechanisms. Scientific Director of Mila and Professor at the University of Montreal.',
    avatarUrl: 'https://commons.wikimedia.org/wiki/File:Yoshua_Bengio_2019_cropped.jpg',
    dataAiHint: 'Yoshua Bengio',
    expertise: ['Deep Learning', 'Neural Networks', 'Reinforcement Learning', 'Recurrent Neural Networks', 'Attention Mechanisms'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'Mila / University of Montreal',
  },
  {
    id: '10',
    name: 'Jürgen Schmidhuber',
    title: 'Director, NNAISENSE / IDSIA',
    bio: 'A pioneering researcher in deep learning, best known for developing Long Short-Term Memory (LSTM) networks, crucial for sequence modeling. Associated with NNAISENSE and IDSIA.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Jürgen Schmidhuber',
    expertise: ['Deep Learning', 'Neural Networks', 'LSTM', 'Sequence Modeling'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'NNAISENSE / IDSIA',
  },
  {
    id: '11',
    name: 'Michael I. Jordan',
    title: 'Distinguished Professor, UC Berkeley',
    bio: 'A leading figure in machine learning, statistics, and artificial intelligence, with extensive contributions to the theoretical foundations of the field. Professor at UC Berkeley.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Michael I.',
    expertise: ['Machine Learning', 'Statistics', 'AI Theory', 'Probabilistic Models'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'UC Berkeley',
  },
  {
    id: '12',
    name: 'Stuart Russell',
    title: 'Professor of Computer Science, UC Berkeley',
    bio: 'Co-author of the seminal textbook "Artificial Intelligence: A Modern Approach," shaping AI education worldwide. Professor at UC Berkeley.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Stuart Russell',
    expertise: ['Artificial Intelligence', 'AI Ethics', 'AI Education', 'Rationality'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'UC Berkeley',
  },
  {
    id: '13',
    name: 'Peter Norvig',
    title: 'Distinguished Education Fellow, Stanford / Google Fellow',
    bio: 'Co-author of "Artificial Intelligence: A Modern Approach" and former Director of Research at Google, known for his work in AI and education. Affiliated with Stanford and Google.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Peter Norvig',
    expertise: ['Artificial Intelligence', 'AI Education', 'Search Algorithms', 'Natural Language Processing'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'Stanford / Google',
  },
  {
    id: '14',
    name: 'Rodney Brooks',
    title: 'Co-founder & CTO, Robust.AI / Professor Emeritus, MIT',
    bio: 'A pioneer in robotics and behavior-based AI, significantly influencing modern robotics design. Co-founder of Robust.AI and Professor Emeritus at MIT.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Rodney Brooks',
    expertise: ['Robotics', 'Behavior-based AI', 'Embodied AI', 'Artificial Intelligence'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'Robust.AI / MIT',
  },
  {
    id: '15',
    name: 'Sebastian Thrun',
    title: 'Founder, Kitty Hawk / Professor, Stanford / Founder, Udacity',
    bio: 'Led Google\'s self-driving car project and founded Udacity, revolutionizing online education in AI and tech. Associated with Kitty Hawk and Stanford.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Sebastian Thrun',
    expertise: ['Robotics', 'Self-Driving Cars', 'AI Education', 'Machine Learning'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'Kitty Hawk / Stanford / Udacity',
  },
  {
    id: '16',
    name: 'Daphne Koller',
    title: 'Founder & CEO, Insitro / Professor Emerita, Stanford / Co-founder, Coursera',
    bio: 'A leading researcher in probabilistic graphical models and their application in biology and health. Co-founded Coursera and founded Insitro. Professor Emerita at Stanford.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Daphne Koller',
    expertise: ['Machine Learning', 'Probabilistic Models', 'Computational Biology', 'AI Education', 'Genomics'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'Insitro / Stanford / Coursera',
  },
  {
    id: '17',
    name: 'Terrence Sejnowski',
    title: 'Professor, Salk Institute / UCSD',
    bio: 'A pioneer in neural networks and computational neuroscience, bridging the gap between AI and brain research. Affiliated with the Salk Institute and UCSD.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Terrence Sejnowski',
    expertise: ['Neural Networks', 'Computational Neuroscience', 'Machine Learning', 'Deep Learning'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'Salk Institute / UCSD',
  },
  {
    id: '18',
    name: 'Fei-Fei Li',
    title: 'Co-Director, Stanford HAI',
    bio: 'Renowned for her work on ImageNet, which significantly advanced computer vision, and for championing human-centered AI and AI for Good. Co-Director of Stanford Human-Centered AI Institute (HAI).',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Fei-Fei Li',
    expertise: ['Computer Vision', 'Machine Learning', 'AI Ethics', 'AI for Good', 'ImageNet'],
    impactArea: 'Pioneers & Foundational Researchers',
    predictions: [],
    company: 'Stanford HAI',
  },
  {
    id: '19',
    name: 'Demis Hassabis',
    title: 'CEO, Google DeepMind',
    bio: 'Co-founder and CEO of Google DeepMind, a neuroscientist and AI researcher leading efforts in AGI and impactful AI applications.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Demis Hassabis',
    expertise: ['AGI Research', 'Neuroscience', 'Machine Learning', 'AI Leadership', 'Game AI'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google DeepMind',
  },
  {
    id: '20',
    name: 'Ilya Sutskever',
    title: 'Co-founder (formerly Chief Scientist, OpenAI)',
    bio: 'A key figure in deep learning, co-founder of OpenAI, and instrumental in many of its significant breakthroughs. Formerly Chief Scientist at OpenAI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Ilya Sutskever',
    expertise: ['Deep Learning', 'Neural Networks', 'AGI Research', 'Generative Models', 'Sequence Modeling'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'OpenAI (formerly)',
  },
  {
    id: '21',
    name: 'Sam Altman',
    title: 'CEO, OpenAI',
    bio: 'CEO of OpenAI, leading one of the most influential AI research and deployment companies in the world.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Sam Altman',
    expertise: ['AI Leadership', 'AI Strategy', 'Technology Entrepreneurship', 'AI Investment'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'OpenAI',
  },
  {
    id: '22',
    name: 'Greg Brockman',
    title: 'President & Co-founder, OpenAI',
    bio: 'Co-founder and President of OpenAI, playing a crucial role in its development and technological advancements.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Greg Brockman',
    expertise: ['AI Leadership', 'Software Engineering', 'AI Strategy', 'Machine Learning Infrastructure'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'OpenAI',
  },
  {
    id: '23',
    name: 'Jeff Dean',
    title: 'Lead, Google AI',
    bio: 'A principal architect of many of Google\'s large-scale distributed systems and AI infrastructure, including MapReduce, BigTable, and TensorFlow. Leads Google AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Jeff Dean',
    expertise: ['Large-Scale Systems', 'Deep Learning', 'Machine Learning Infrastructure', 'Distributed Systems', 'TensorFlow'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google AI',
  },
  {
    id: '24',
    name: 'Shane Legg',
    title: 'Co-founder & Chief AGI Scientist, Google DeepMind',
    bio: 'Co-founder of DeepMind and its Chief AGI Scientist, focused on the long-term goal of creating Artificial General Intelligence.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Shane Legg',
    expertise: ['AGI Research', 'Machine Learning', 'AI Theory', 'Reinforcement Learning'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google DeepMind',
  },
  {
    id: '25',
    name: 'Mustafa Suleyman',
    title: 'CEO, Microsoft AI',
    bio: 'Co-founder of DeepMind and Inflection AI, now leading Microsoft\'s AI division as CEO.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Mustafa Suleyman',
    expertise: ['AI Leadership', 'Applied AI', 'AI Ethics', 'AI Strategy', 'AGI Research'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Microsoft AI (formerly DeepMind, Inflection AI)',
  },
  {
    id: '26',
    name: 'Joelle Pineau',
    title: 'VP AI Research, Meta / Professor, McGill University',
    bio: 'An expert in reinforcement learning and dialogue systems, leading AI research at Meta and holding a professorship at McGill University.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Joelle Pineau',
    expertise: ['Reinforcement Learning', 'Dialogue Systems', 'Robotics', 'AI Research', 'Machine Learning'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Meta / McGill University',
  },
  {
    id: '27',
    name: 'Andrej Karpathy',
    title: 'AI Researcher',
    bio: 'A founding member of OpenAI and former Director of AI at Tesla, known for significant contributions to computer vision and deep learning education.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Andrej Karpathy',
    expertise: ['Computer Vision', 'Deep Learning', 'AI Education', 'Neural Networks', 'Self-Driving Cars'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'OpenAI (Founding Member) / Tesla (formerly)',
  },
  {
    id: '28',
    name: 'Oriol Vinyals',
    title: 'Research Director, Google DeepMind',
    bio: 'Prominent researcher at Google DeepMind, known for work on sequence-to-sequence models, reinforcement learning, and large language models.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Oriol Vinyals',
    expertise: ['Deep Learning', 'Reinforcement Learning', 'Natural Language Processing', 'Sequence Modeling', 'AGI Research'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google DeepMind',
  },
  {
    id: '29',
    name: 'John Schulman',
    title: 'Co-founder, OpenAI',
    bio: 'Co-founder of OpenAI, with key contributions to reinforcement learning algorithms like PPO and TRPO.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'John Schulman',
    expertise: ['Reinforcement Learning', 'Deep Learning', 'Robotics', 'Optimization', 'PPO', 'TRPO'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'OpenAI',
  },
  {
    id: '30',
    name: 'Wojciech Zaremba',
    title: 'Co-founder, OpenAI',
    bio: 'Co-founder of OpenAI, focusing on robotics, generative models, and advancing AI capabilities.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Wojciech Zaremba',
    expertise: ['Robotics', 'Generative Models', 'Deep Learning', 'AGI Research', 'Reinforcement Learning'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'OpenAI',
  },
  {
    id: '31',
    name: 'Nando de Freitas',
    title: 'Research Scientist, Google DeepMind',
    bio: 'Influential research scientist at Google DeepMind, working on deep learning, reinforcement learning, and Bayesian inference.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Nando de',
    expertise: ['Deep Learning', 'Reinforcement Learning', 'Machine Learning', 'Bayesian Methods', 'Neural Networks'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google DeepMind',
  },
  {
    id: '32',
    name: 'Raia Hadsell',
    title: 'Director of Robotics, Google DeepMind',
    bio: 'Leads robotics research at Google DeepMind, focusing on continual learning, navigation, and robot perception.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Raia Hadsell',
    expertise: ['Robotics', 'Reinforcement Learning', 'Machine Learning', 'Continual Learning', 'Navigation'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google DeepMind',
  },
  {
    id: '33',
    name: 'Pushmeet Kohli',
    title: 'Head of AI for Science, Google DeepMind',
    bio: 'Heads Google DeepMind\'s AI for Science initiative, applying AI to solve complex scientific problems, notably in biology (e.g., AlphaFold).',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Pushmeet Kohli',
    expertise: ['AI for Science', 'Machine Learning', 'Computer Vision', 'Computational Biology', 'AlphaFold'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google DeepMind',
  },
  {
    id: '34',
    name: 'Samy Bengio',
    title: 'Senior Director of AI and ML Research, Apple',
    bio: 'An experienced AI researcher leading AI and ML research at Apple, formerly a distinguished scientist at Google.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Samy Bengio',
    expertise: ['Machine Learning', 'Deep Learning', 'AI Research', 'Computer Vision', 'Speech Recognition'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Apple (formerly Google)',
  },
  {
    id: '35',
    name: 'Zoubin Ghahramani',
    title: 'VP of Research, Google AI / Professor, University of Cambridge',
    bio: 'Leads research at Google AI and is a Professor at the University of Cambridge, with expertise in Bayesian machine learning and AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Zoubin Ghahramani',
    expertise: ['Machine Learning', 'Bayesian Methods', 'AI Research', 'Statistics', 'Probabilistic Models'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google AI / University of Cambridge',
  },
  {
    id: '36',
    name: 'Eric Horvitz',
    title: 'Chief Scientific Officer, Microsoft',
    bio: 'Microsoft\'s Chief Scientific Officer, with extensive work on AI principles, human-AI collaboration, and the societal impacts of AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Eric Horvitz',
    expertise: ['Artificial Intelligence', 'Human-AI Collaboration', 'AI Ethics', 'Decision Theory', 'AI Policy'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Microsoft',
  },
  {
    id: '37',
    name: 'Xuedong Huang',
    title: 'Azure AI CTO, Microsoft Technical Fellow',
    bio: 'Microsoft Technical Fellow and CTO for Azure AI, a pioneer in speech recognition and AI platforms.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Xuedong Huang',
    expertise: ['Speech Recognition', 'AI Platforms', 'Machine Learning', 'Natural Language Processing', 'Deep Learning'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Microsoft',
  },
  {
    id: '38',
    name: 'Jianfeng Gao',
    title: 'Distinguished Scientist, VP, Microsoft Research',
    bio: 'Distinguished Scientist and VP at Microsoft Research, focusing on natural language processing, deep learning, and large language models.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Jianfeng Gao',
    expertise: ['Natural Language Processing', 'Deep Learning', 'Large Language Models', 'Machine Translation'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Microsoft Research',
  },
  {
    id: '39',
    name: 'Alex Smola',
    title: 'VP/Distinguished Scientist, Amazon Web Services / Professor, CMU',
    bio: 'VP and Distinguished Scientist at AWS, and Professor at CMU, with expertise in machine learning, deep learning, and scalable AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Alex Smola',
    expertise: ['Machine Learning', 'Deep Learning', 'Scalable AI', 'Optimization', 'Kernel Methods'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Amazon Web Services / Carnegie Mellon University',
  },
  {
    id: '40',
    name: 'Manuela Veloso',
    title: 'Head of J.P. Morgan AI Research / Professor Emerita, CMU',
    bio: 'Leads AI Research at J.P. Morgan and is Professor Emerita at CMU, a pioneer in autonomous robots and symbiotic human-robot interaction.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Manuela Veloso',
    expertise: ['Robotics', 'Artificial Intelligence', 'Machine Learning', 'Human-Robot Interaction', 'AI Planning'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'J.P. Morgan AI Research / Carnegie Mellon University',
  },
  {
    id: '41',
    name: 'Aidan Gomez',
    title: 'CEO, Cohere',
    bio: 'CEO of Cohere and a co-author of the influential "Attention Is All You Need" paper, which introduced the Transformer architecture.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Aidan Gomez',
    expertise: ['Natural Language Processing', 'Transformers', 'Large Language Models', 'AI Entrepreneurship', 'Deep Learning'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Cohere',
  },
  {
    id: '42',
    name: 'Noam Shazeer',
    title: 'CEO, Character.ai',
    bio: 'CEO of Character.ai, co-author of "Attention Is All You Need," and key contributor to large-scale neural networks at Google.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Noam Shazeer',
    expertise: ['Natural Language Processing', 'Transformers', 'Large Language Models', 'AI Entrepreneurship', 'Large-Scale Systems'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Character.ai (formerly Google)',
  },
  {
    id: '43',
    name: 'Ashish Vaswani',
    title: 'CEO, Essential AI',
    bio: 'CEO of Essential AI and lead author of the "Attention Is All You Need" paper, fundamental to modern NLP. Formerly at Google.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Ashish Vaswani',
    expertise: ['Natural Language Processing', 'Transformers', 'Deep Learning', 'AI Entrepreneurship', 'Sequence Modeling'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Essential AI (formerly Google)',
  },
  {
    id: '44',
    name: 'Jakob Uszkoreit',
    title: 'CEO, Inceptive',
    bio: 'CEO of Inceptive and co-author of "Attention Is All You Need." Formerly a key researcher at Google Brain.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Jakob Uszkoreit',
    expertise: ['Natural Language Processing', 'Transformers', 'Computational Biology', 'AI Entrepreneurship', 'Deep Learning'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Inceptive (formerly Google)',
  },
  {
    id: '45',
    name: 'Llion Jones',
    title: 'Co-founder, Sakana AI',
    bio: 'Co-author of "Attention Is All You Need" while at Google, now co-founder of Sakana AI, focusing on new AI architectures.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Llion Jones',
    expertise: ['Natural Language Processing', 'Transformers', 'AI Architectures', 'Deep Learning'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Sakana AI (formerly Google)',
  },
  {
    id: '46',
    name: 'Illia Polosukhin',
    title: 'Co-founder, NEAR Protocol',
    bio: 'Co-founder of NEAR Protocol and co-author of "Attention Is All You Need." Contributed to TensorFlow at Google.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Illia Polosukhin',
    expertise: ['Blockchain', 'Natural Language Processing', 'Transformers', 'Decentralized Systems', 'TensorFlow'],
    impactArea: 'Pioneers & Foundational Researchers', // Reclassified based on diverse impact
    predictions: [],
    company: 'NEAR Protocol (formerly Google)',
  },
  {
    id: '47',
    name: 'Niki Parmar',
    title: 'Co-founder, Essential AI',
    bio: 'Co-founder of Essential AI and co-author of "Attention Is All You Need." Formerly a researcher at Google Brain.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Niki Parmar',
    expertise: ['Natural Language Processing', 'Transformers', 'Deep Learning', 'AI Entrepreneurship', 'Computer Vision'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Essential AI (formerly Google)',
  },
  {
    id: '48',
    name: 'Lukasz Kaiser',
    title: 'Researcher, OpenAI',
    bio: 'Co-author of "Attention Is All You Need" and the Tensor2Tensor library while at Google. Now a researcher at OpenAI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Lukasz Kaiser',
    expertise: ['Deep Learning', 'Natural Language Processing', 'Transformers', 'Machine Learning Systems', 'Tensor2Tensor'],
    impactArea: 'Pioneers & Foundational Researchers', // Reclassified based on fundamental contributions
    predictions: [],
    company: 'OpenAI (formerly Google)',
  },
  {
    id: '49',
    name: 'David Silver',
    title: 'Principal Research Scientist, Google DeepMind',
    bio: 'Led the AlphaGo project, which defeated a world champion Go player, and subsequent projects like AlphaZero and AlphaStar at Google DeepMind.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'David Silver',
    expertise: ['Reinforcement Learning', 'Deep Learning', 'Game AI', 'AGI Research', 'AlphaGo', 'AlphaZero'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google DeepMind',
  },
  {
    id: '50',
    name: 'Vladlen Koltun',
    title: 'Distinguished Scientist, Apple',
    bio: 'A distinguished scientist at Apple, previously at Intel Labs, known for contributions to computer vision, deep learning, and robotics.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Vladlen Koltun',
    expertise: ['Computer Vision', 'Deep Learning', 'Robotics', '3D Reconstruction', 'Simulation'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Apple (formerly Intel Labs)',
  },
  {
    id: '51',
    name: 'Andrew Ng',
    title: 'Founder, Landing AI / General Partner, AI Fund / Co-founder, Coursera / Adjunct Professor, Stanford',
    bio: 'A leading figure in deep learning and online education. Co-founded Coursera and Google Brain. Founder of Landing AI and AI Fund.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Andrew Ng',
    expertise: ['Deep Learning', 'Machine Learning', 'AI Education', 'AI Strategy', 'Online Education'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Landing AI / AI Fund / Coursera / Stanford University',
  },
  {
    id: '52',
    name: 'Pieter Abbeel',
    title: 'Professor, UC Berkeley / Co-founder, Covariant',
    bio: 'Professor at UC Berkeley and co-founder of Covariant, specializing in robotics, reinforcement learning, and deep learning for robot control.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Pieter Abbeel',
    expertise: ['Robotics', 'Reinforcement Learning', 'Deep Learning', 'AI Entrepreneurship', 'Robot Learning'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'UC Berkeley / Covariant',
  },
  {
    id: '53',
    name: 'Anima Anandkumar',
    title: 'Bren Professor, Caltech / Sr. Director of AI Research, NVIDIA',
    bio: 'Bren Professor at Caltech and Senior Director of AI Research at NVIDIA, working on tensor methods, deep learning, and large-scale machine learning.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Anima Anandkumar',
    expertise: ['Machine Learning', 'Deep Learning', 'Tensor Methods', 'High-Performance Computing', 'AI for Science'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Caltech / NVIDIA',
  },
  {
    id: '54',
    name: 'Percy Liang',
    title: 'Associate Professor, Stanford HAI',
    bio: 'Associate Professor at Stanford and affiliated with HAI, focusing on natural language processing, trustworthy AI, and machine learning.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Percy Liang',
    expertise: ['Natural Language Processing', 'Trustworthy AI', 'Machine Learning', 'AI Ethics', 'Foundation Models'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Stanford HAI',
  },
  {
    id: '55',
    name: 'Chris Manning',
    title: 'Professor of Linguistics and Computer Science, Stanford',
    bio: 'Leading researcher in natural language processing at Stanford, known for deep learning approaches to NLP and co-author of influential textbooks.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Chris Manning',
    expertise: ['Natural Language Processing', 'Deep Learning', 'Computational Linguistics', 'Sentiment Analysis'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Stanford University',
  },
  {
    id: '56',
    name: 'Daniela Rus',
    title: 'Director, MIT CSAIL / Professor, MIT',
    bio: 'Director of MIT CSAIL and Professor at MIT, a prominent researcher in robotics, mobile computing, and distributed systems.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Daniela Rus',
    expertise: ['Robotics', 'Mobile Computing', 'Distributed Systems', 'AI Leadership', 'Networked Systems'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'MIT CSAIL',
  },
  {
    id: '57',
    name: 'Yejin Choi',
    title: 'Professor, University of Washington / Senior Research Director, AI2',
    bio: 'Professor at the University of Washington and Senior Research Director at AI2. MacArthur Fellow known for work in NLP, commonsense reasoning, and AI ethics.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Yejin Choi',
    expertise: ['Natural Language Processing', 'Commonsense Reasoning', 'AI Ethics', 'Computational Linguistics', 'Neuro-Symbolic AI'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'University of Washington / Allen Institute for AI (AI2)',
  },
  {
    id: '58',
    name: 'Chelsea Finn',
    title: 'Assistant Professor, Stanford University',
    bio: 'Assistant Professor at Stanford, researching meta-learning, reinforcement learning, and robotics, enabling robots to quickly learn new skills.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Chelsea Finn',
    expertise: ['Meta-Learning', 'Reinforcement Learning', 'Robotics', 'Machine Learning', 'Deep Learning'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Stanford University',
  },
  {
    id: '59',
    name: 'Raquel Urtasun',
    title: 'Professor, University of Toronto / CEO, Waabi',
    bio: 'Professor at the University of Toronto and CEO of Waabi, focusing on machine perception for self-driving vehicles.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Raquel Urtasun',
    expertise: ['Computer Vision', 'Self-Driving Cars', 'Machine Learning', 'AI Entrepreneurship', '3D Perception'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'University of Toronto / Waabi',
  },
  {
    id: '60',
    name: 'Ruslan Salakhutdinov',
    title: 'Professor, Carnegie Mellon University',
    bio: 'Professor at CMU, formerly Director of AI Research at Apple. Known for contributions to deep learning, graphical models, and large-scale ML.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Ruslan Salakhutdinov',
    expertise: ['Deep Learning', 'Machine Learning', 'Graphical Models', 'AI Research', 'Generative Models'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Carnegie Mellon University (formerly Apple)',
  },
  {
    id: '61',
    name: 'Bernhard Schölkopf',
    title: 'Director, Max Planck Institute for Intelligent Systems',
    bio: 'Director at the Max Planck Institute for Intelligent Systems, a leading researcher in kernel methods, causal inference, and machine learning.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Bernhard Schölkopf',
    expertise: ['Machine Learning', 'Kernel Methods', 'Causal Inference', 'AI Theory', 'Computational Photography'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Max Planck Institute for Intelligent Systems',
  },
  {
    id: '62',
    name: 'Max Welling',
    title: 'Professor, University of Amsterdam / Distinguished Scientist, Microsoft Research',
    bio: 'Professor at the University of Amsterdam and Distinguished Scientist at Microsoft Research, focusing on graphical models, deep learning, and Bayesian methods.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Max Welling',
    expertise: ['Machine Learning', 'Deep Learning', 'Graphical Models', 'Bayesian Methods', 'Physics-informed AI'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'University of Amsterdam / Microsoft Research',
  },
  {
    id: '63',
    name: 'Leslie Kaelbling',
    title: 'Professor, MIT',
    bio: 'Professor at MIT, a pioneer in reinforcement learning, decision making under uncertainty, and robotics.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Leslie Kaelbling',
    expertise: ['Reinforcement Learning', 'Robotics', 'AI Planning', 'Decision Making', 'Probabilistic AI'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'MIT',
  },
  {
    id: '64',
    name: 'Pedro Domingos',
    title: 'Professor Emeritus, University of Washington',
    bio: 'Professor Emeritus at the University of Washington and author of "The Master Algorithm," known for work in machine learning and knowledge representation.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Pedro Domingos',
    expertise: ['Machine Learning', 'AI Theory', 'Knowledge Representation', 'Markov Logic Networks'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'University of Washington',
  },
  {
    id: '65',
    name: 'Tomas Mikolov',
    title: 'Researcher, CIIRC CTU',
    bio: 'Known for creating Word2Vec, a highly influential technique for word embeddings in NLP. Formerly at Facebook AI Research and Google.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Tomas Mikolov',
    expertise: ['Natural Language Processing', 'Word Embeddings', 'Deep Learning', 'Recurrent Neural Networks'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'CIIRC CTU (formerly Facebook, Google)',
  },
  {
    id: '66',
    name: 'Been Kim',
    title: 'Staff Research Scientist, Google DeepMind',
    bio: 'Researcher at Google DeepMind focusing on interpretability and explainable AI (XAI), making complex AI models more understandable.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Been Kim',
    expertise: ['Interpretability', 'Explainable AI', 'Machine Learning', 'AI Ethics', 'Human-AI Collaboration'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Google DeepMind',
  },
  {
    id: '67',
    name: 'Cynthia Rudin',
    title: 'Professor, Duke University',
    bio: 'Professor at Duke University, a leading advocate and researcher in interpretable machine learning and causal inference.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Cynthia Rudin',
    expertise: ['Interpretable Machine Learning', 'Causal Inference', 'AI Ethics', 'Explainable AI'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Duke University',
  },
  {
    id: '68',
    name: 'Shuran Song',
    title: 'Assistant Professor, Columbia University',
    bio: 'Assistant Professor at Columbia University, researching robotics, 3D computer vision, and robot learning.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Shuran Song',
    expertise: ['Robotics', '3D Computer Vision', 'Machine Learning', 'Robot Learning', 'Embodied AI'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Columbia University',
  },
  {
    id: '69',
    name: 'Jitendra Malik',
    title: 'Professor, UC Berkeley / Research Scientist, Meta AI',
    bio: 'Professor at UC Berkeley and Research Scientist at Meta AI, a leading figure in computer vision.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Jitendra Malik',
    expertise: ['Computer Vision', 'Machine Learning', 'Image Recognition', 'Computational Photography'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'UC Berkeley / Meta AI',
  },
  {
    id: '70',
    name: 'Alexei Efros',
    title: 'Professor, UC Berkeley',
    bio: 'Professor at UC Berkeley, known for his influential work in computer vision, computational photography, and texture synthesis.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Alexei Efros',
    expertise: ['Computer Vision', 'Computational Photography', 'Graphics', 'Machine Learning', 'Image Synthesis'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'UC Berkeley',
  },
  {
    id: '71',
    name: 'Devi Parikh',
    title: 'Associate Professor, Georgia Tech / Research Scientist, Meta AI',
    bio: 'Associate Professor at Georgia Tech and Research Scientist at Meta AI, working on computer vision, NLP, and AI for creativity.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Devi Parikh',
    expertise: ['Computer Vision', 'Natural Language Processing', 'AI for Creativity', 'Machine Learning', 'Explainable AI'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'Georgia Tech / Meta AI',
  },
  {
    id: '72',
    name: 'Kyunghyun Cho',
    title: 'Associate Professor, NYU / Research Scientist, Genentech',
    bio: 'Associate Professor at NYU and Research Scientist at Genentech, known for his contributions to NLP, machine translation, and Gated Recurrent Units (GRUs).',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Kyunghyun Cho',
    expertise: ['Natural Language Processing', 'Machine Translation', 'Deep Learning', 'Neural Networks', 'GRUs'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'NYU / Genentech',
  },
  {
    id: '73',
    name: 'Sanjoy Dasgupta',
    title: 'Professor, UC San Diego',
    bio: 'Professor at UC San Diego, specializing in theoretical machine learning, clustering, and active learning.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Sanjoy Dasgupta',
    expertise: ['Theoretical Machine Learning', 'Algorithms', 'Statistics', 'Clustering', 'Active Learning'],
    impactArea: 'Influential Academics',
    predictions: [],
    company: 'UC San Diego',
  },
  {
    id: '74',
    name: 'Jensen Huang',
    title: 'CEO, NVIDIA',
    bio: 'Co-founder and CEO of NVIDIA, whose GPUs have become foundational for the AI revolution, enabling large-scale deep learning.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Jensen Huang',
    expertise: ['GPU Technology', 'AI Hardware', 'Deep Learning Infrastructure', 'AI Leadership', 'High-Performance Computing'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'NVIDIA',
  },
  {
    id: '75',
    name: 'Richard Socher',
    title: 'CEO, You.com',
    bio: 'CEO of You.com and former Chief Scientist at Salesforce, known for his work in NLP, deep learning, and recursive neural networks.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Richard Socher',
    expertise: ['Natural Language Processing', 'Deep Learning', 'Search Technology', 'AI Entrepreneurship', 'Recursive Neural Networks'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'You.com (formerly Salesforce)',
  },
  {
    id: '76',
    name: 'Clément Delangue',
    title: 'CEO, Hugging Face',
    bio: 'Co-founder and CEO of Hugging Face, a company central to democratizing NLP and making large models accessible.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Clément Delangue',
    expertise: ['Natural Language Processing', 'Open Source AI', 'Democratizing AI', 'AI Entrepreneurship', 'Large Language Models'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Hugging Face',
  },
  {
    id: '77',
    name: 'Alex Krizhevsky',
    title: 'AI Researcher',
    bio: 'Creator of AlexNet, a convolutional neural network that significantly advanced image recognition and was pivotal in deep learning\'s resurgence. Formerly at Google.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Alex Krizhevsky',
    expertise: ['Deep Learning', 'Computer Vision', 'Neural Networks', 'Image Recognition', 'AlexNet'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Formerly Google',
  },
  {
    id: '78',
    name: 'Ian Goodfellow',
    title: 'AI Researcher, Apple',
    bio: 'Inventor of Generative Adversarial Networks (GANs), a major breakthrough in generative modeling. Has worked at Apple, Google, and OpenAI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Ian Goodfellow',
    expertise: ['Generative Models', 'GANs', 'Deep Learning', 'AI Security', 'Neural Networks'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Apple (formerly Google, OpenAI)',
  },
  {
    id: '79',
    name: 'Aravind Srinivas',
    title: 'CEO, Perplexity AI',
    bio: 'Co-founder and CEO of Perplexity AI, developing conversational AI search engines.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Aravind Srinivas',
    expertise: ['Natural Language Processing', 'Search Technology', 'AI Entrepreneurship', 'Large Language Models', 'Conversational AI'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Perplexity AI',
  },
  {
    id: '80',
    name: 'Jonas Andrulis',
    title: 'CEO, Aleph Alpha',
    bio: 'Founder and CEO of Aleph Alpha, a European company focused on developing large language models and sovereign AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Jonas Andrulis',
    expertise: ['Large Language Models', 'AI Entrepreneurship', 'AI Strategy', 'European AI', 'Explainable AI'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Aleph Alpha',
  },
  {
    id: '81',
    name: 'Arthur Mensch',
    title: 'CEO, Mistral AI',
    bio: 'Co-founder and CEO of Mistral AI, a prominent European AI startup developing open and efficient large language models.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Arthur Mensch',
    expertise: ['Large Language Models', 'AI Entrepreneurship', 'Open Source AI', 'European AI', 'Efficient AI Models'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Mistral AI',
  },
  {
    id: '82',
    name: 'Chris Urmson',
    title: 'CEO, Aurora',
    bio: 'CEO of Aurora, a self-driving technology company. Formerly led Google\'s self-driving car project (Waymo).',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Chris Urmson',
    expertise: ['Self-Driving Cars', 'Robotics', 'AI Leadership', 'AI Entrepreneurship', 'Autonomous Systems'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Aurora (formerly Google Self-Driving)',
  },
  {
    id: '83',
    name: 'Adam D\'Angelo',
    title: 'CEO, Quora / Founder, Poe',
    bio: 'CEO of Quora and founder of Poe, a platform for interacting with various AI chatbots. Former CTO of Facebook.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Adam D\'Angelo',
    expertise: ['AI Platforms', 'Consumer AI', 'Social Technology', 'AI Entrepreneurship', 'Large Language Models'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Quora / Poe',
  },
  {
    id: '84',
    name: 'Alex Kendall',
    title: 'CEO, Wayve',
    bio: 'Co-founder and CEO of Wayve, a company pioneering end-to-end deep learning for autonomous driving.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Alex Kendall',
    expertise: ['Self-Driving Cars', 'Deep Learning', 'Robotics', 'AI Entrepreneurship', 'Embodied AI'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Wayve',
  },
  {
    id: '85',
    name: 'Anna Patterson',
    title: 'Managing Partner, Gradient Ventures',
    bio: 'Managing Partner at Gradient Ventures (Google\'s AI-focused venture fund) and former VP of Engineering at Google.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Anna Patterson',
    expertise: ['AI Investment', 'Venture Capital', 'Search Technology', 'AI Startups', 'AI Leadership'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'Gradient Ventures (Google)',
  },
  {
    id: '86',
    name: 'Clara Shih',
    title: 'CEO, Salesforce AI',
    bio: 'CEO of Salesforce AI, leading the integration of AI across Salesforce products and driving enterprise AI adoption.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Clara Shih',
    expertise: ['Enterprise AI', 'AI Strategy', 'CRM Technology', 'AI Leadership', 'Applied AI'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Salesforce AI',
  },
  {
    id: '87',
    name: 'Marc Raibert',
    title: 'Executive Director, The AI Institute / Founder, Boston Dynamics',
    bio: 'Founder of Boston Dynamics, renowned for creating highly advanced and dynamic robots. Now Executive Director of The AI Institute.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Marc Raibert',
    expertise: ['Robotics', 'Dynamic Control Systems', 'AI Hardware', 'AI Leadership', 'Legged Locomotion'],
    impactArea: 'Key Innovators & Entrepreneurs',
    predictions: [],
    company: 'The AI Institute / Boston Dynamics',
  },
  {
    id: '88',
    name: 'Timnit Gebru',
    title: 'Founder & Executive Director, DAIR Institute',
    bio: 'Founder of the Distributed AI Research (DAIR) Institute, a prominent voice in AI ethics, algorithmic bias, and fairness. Formerly at Google.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Timnit Gebru',
    expertise: ['AI Ethics', 'Algorithmic Bias', 'Fairness in AI', 'AI Policy', 'Accountability'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'DAIR Institute (formerly Google)',
  },
  {
    id: '89',
    name: 'Joy Buolamwini',
    title: 'Founder, Algorithmic Justice League',
    bio: 'Founder of the Algorithmic Justice League, known for exposing bias in facial recognition technology and advocating for equitable AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Joy Buolamwini',
    expertise: ['Algorithmic Bias', 'AI Ethics', 'Facial Recognition Technology', 'AI Policy', 'Social Justice'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'Algorithmic Justice League',
  },
  {
    id: '90',
    name: 'Kate Crawford',
    title: 'Research Professor, USC Annenberg / Sr. Principal Researcher, Microsoft Research',
    bio: 'Leading scholar on the social and political implications of AI, data systems, and artificial intelligence. Affiliated with USC Annenberg and Microsoft Research.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Kate Crawford',
    expertise: ['Social Implications of AI', 'AI Ethics', 'AI Policy', 'Data Studies', 'Power Dynamics'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'USC Annenberg / Microsoft Research',
  },
  {
    id: '91',
    name: 'Oren Etzioni',
    title: 'Founding CEO Emeritus, Allen Institute for AI (AI2) / Professor, University of Washington',
    bio: 'Founding CEO Emeritus of AI2 and Professor at the University of Washington, a significant voice in AI ethics, impact, and commonsense reasoning.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Oren Etzioni',
    expertise: ['AI Ethics', 'AI Impact', 'Commonsense Reasoning', 'AI Leadership', 'Startups'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'Allen Institute for AI (AI2) / University of Washington',
  },
  {
    id: '92',
    name: 'Gary Marcus',
    title: 'Professor Emeritus, NYU / Founder, Robust.AI',
    bio: 'Professor Emeritus at NYU and founder of Robust.AI. A prominent critic of current deep learning approaches and advocate for neuro-symbolic AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Gary Marcus',
    expertise: ['Cognitive Science', 'Neuro-Symbolic AI', 'AI Criticism', 'AI Safety', 'Developmental Psychology'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'NYU / Robust.AI',
  },
  {
    id: '93',
    name: 'Francesca Rossi',
    title: 'IBM AI Ethics Global Leader',
    bio: 'IBM Fellow and AI Ethics Global Leader, working on embedding ethical principles into AI technologies and practices.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Francesca Rossi',
    expertise: ['AI Ethics', 'AI Governance', 'Responsible AI', 'AI Policy', 'Constraint Satisfaction'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'IBM',
  },
  {
    id: '94',
    name: 'Rumman Chowdhury',
    title: 'CEO, Humane Intelligence',
    bio: 'CEO of Humane Intelligence and former Director of ML Ethics, Transparency & Accountability at Twitter, focusing on applied algorithmic ethics.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Rumman Chowdhury',
    expertise: ['Algorithmic Ethics', 'Responsible AI', 'AI Governance', 'AI Policy', 'Bias Mitigation'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'Humane Intelligence (formerly Twitter)',
  },
  {
    id: '95',
    name: 'Eric Schmidt',
    title: 'Former CEO, Google / Chair, NSCAI',
    bio: 'Former CEO of Google and Chair of the National Security Commission on Artificial Intelligence (NSCAI), influential in AI policy and national security discussions.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Eric Schmidt',
    expertise: ['AI Policy', 'National Security', 'Technology Leadership', 'AI Strategy', 'Government'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'Formerly Google, NSCAI',
  },
  {
    id: '96',
    name: 'James Manyika',
    title: 'SVP, Research, Technology & Society, Google',
    bio: 'Senior Vice President at Google, focusing on the economic and societal impact of technology, including AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'James Manyika',
    expertise: ['Societal Impact of AI', 'AI Economics', 'AI Policy', 'Technology Research', 'Future of Work'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'Google',
  },
  {
    id: '97',
    name: 'DJ Patil',
    title: 'Executive, Devoted Health',
    bio: 'Former U.S. Chief Data Scientist, a leading voice in data ethics, AI for good, and applying data science to solve societal challenges. Now at Devoted Health.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'DJ Patil',
    expertise: ['Data Ethics', 'AI for Good', 'Data Science', 'Healthcare AI', 'Public Policy'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'Devoted Health (formerly U.S. Government)',
  },
  {
    id: '98',
    name: 'Helen Toner',
    title: 'Director of Strategy, Center for Security and Emerging Technology (CSET)',
    bio: 'Director of Strategy at CSET and former OpenAI board member, focusing on AI policy, safety, and US-China tech competition.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Helen Toner',
    expertise: ['AI Policy', 'AI Safety', 'Technology Governance', 'International Security', 'China AI'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'Center for Security and Emerging Technology (CSET) (formerly OpenAI board)',
  },
  {
    id: '99',
    name: 'Eliezer Yudkowsky',
    title: 'Co-founder & Research Fellow, Machine Intelligence Research Institute (MIRI)',
    bio: 'Co-founder of MIRI, a prominent researcher and writer on AI alignment, superintelligence, and existential risk from advanced AI.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Eliezer Yudkowsky',
    expertise: ['AI Alignment', 'Existential Risk', 'AI Safety', 'Rationality', 'Decision Theory'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'Machine Intelligence Research Institute (MIRI)',
  },
  {
    id: '100',
    name: 'Nick Bostrom',
    title: 'Professor, University of Oxford / Director, Future of Humanity Institute',
    bio: 'Professor at Oxford University and Director of the Future of Humanity Institute, author of "Superintelligence," focusing on AI safety and existential risk.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Nick Bostrom',
    expertise: ['AI Safety', 'Existential Risk', 'Superintelligence', 'Philosophy of AI', 'Transhumanism'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'University of Oxford / Future of Humanity Institute',
  },
  {
    id: '101',
    name: 'Max Tegmark',
    title: 'Professor, MIT / President, Future of Life Institute',
    bio: 'Professor at MIT and President of the Future of Life Institute, a physicist and AI safety advocate, author of "Life 3.0."',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Max Tegmark',
    expertise: ['AI Safety', 'Physics', 'Existential Risk', 'Future of AI', 'Consciousness'],
    impactArea: 'Prominent Voices in AI Ethics & Safety',
    predictions: [],
    company: 'MIT / Future of Life Institute',
  },
  {
    id: '102',
    name: 'Noam Brown',
    title: 'Research Scientist, Meta AI',
    bio: 'Research Scientist at Meta AI, known for developing AI that achieved superhuman performance in complex games like Poker (Pluribus) and Diplomacy (Cicero).',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Noam Brown',
    expertise: ['Game AI', 'Reinforcement Learning', 'Multi-Agent Systems', 'Deep Learning', 'Computational Game Theory'],
    impactArea: 'Leaders at Major AI Labs & Companies', // Or Key Innovators due to specific breakthroughs
    predictions: [],
    company: 'Meta AI',
  },
  {
    id: '103',
    name: 'Armand Joulin',
    title: 'Research Scientist, Meta AI',
    bio: 'Research Scientist at Meta AI, contributing to efficient NLP models (e.g., fastText) and computer vision.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Armand Joulin',
    expertise: ['Natural Language Processing', 'Computer Vision', 'Efficient AI Models', 'Machine Learning', 'fastText'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Meta AI',
  },
  {
    id: '104',
    name: 'Volodymyr Mnih',
    title: 'Research Scientist, Google DeepMind',
    bio: 'Research Scientist at Google DeepMind, a key figure in developing Deep Q-Networks (DQN), a breakthrough in deep reinforcement learning.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Volodymyr Mnih',
    expertise: ['Reinforcement Learning', 'Deep Learning', 'Neural Networks', 'Game AI', 'Deep Q-Networks (DQN)'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google DeepMind',
  },
  {
    id: '105',
    name: 'Larry Heck',
    title: 'Director, AI, Google',
    bio: 'Director of AI at Google, with extensive experience in speech recognition and conversational AI. Formerly at Samsung and Microsoft.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Larry Heck',
    expertise: ['Speech Recognition', 'Conversational AI', 'Natural Language Processing', 'AI Research', 'Deep Learning'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Google (formerly Samsung, Microsoft)',
  },
  {
    id: '106',
    name: 'Li Deng',
    title: 'Chief AI Officer, Citadel',
    bio: 'Chief AI Officer at Citadel. Formerly Chief AI Officer at Microsoft and Head of AI Research at DeepMind, pioneering deep learning for speech recognition and finance.',
    avatarUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'Li Deng',
    expertise: ['Deep Learning', 'Speech Recognition', 'Financial AI', 'AI Strategy', 'Natural Language Processing'],
    impactArea: 'Leaders at Major AI Labs & Companies',
    predictions: [],
    company: 'Citadel (formerly Microsoft, DeepMind)',
  }
];

export const getAllExpertise = (): string[] => {
  const allExpertise = new Set<string>();
  experts.forEach(expert => {
    expert.expertise.forEach(e => allExpertise.add(e));
  });
  return Array.from(allExpertise).sort();
};

export const getAllImpactAreas = (): string[] => {
  return IMPACT_AREAS_ORDERED;
};
